name: 'BlueBuild'
description: 'Build a custom OS image'
inputs:
  recipe:
    description: |
      The [recipe](https://blue-build.org/reference/recipe/) file to build the image from, relative to the `config/` directory.
    required: true
    default: 'recipe.yml'
  cosign_private_key:
    description: |
      The Sigstore/cosign secret used to sign the image.

      Example: `&#36;{{ secrets.SIGNING_SECRET }}`
    required: true
  registry_token:
    description: | 
      The token used to sign into the container registry.

      Example: `&#36;{{ github.token }}`
    required: true
  pr_event_number:
    description: |
      The event number used to tag images pushed from pull requests.

      Example: `&#36;{{ github.event.number }}`
    required: true
  registry:
    description: |
      The container registry to push the built image to.
    required: false
    default: 'ghcr.io'
  registry_namespace:
    description: |
     The namespace on the registry to push to.
     
     Example: `ublue-os`
    required: false
    default: ${{ github.repository_owner }}
runs:
  using: "composite"
  steps:
    # building custom images might take a lot of space, 
    # so it's best to remove unneeded softawre
    - name: Maximize build space
      uses: ublue-os/remove-unwanted-software@v6

    # clones user's repo
    - uses: actions/checkout@v4

    # deps used by cli to build & inspect imaegs
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y podman

    # blue-build/cli does the heavy lifting
    - name: Build Image
      shell: bash
      env:
        COSIGN_PRIVATE_KEY: ${{ inputs.cosign_private_key }}
        REGISTRY_TOKEN: ${{ inputs.registry_token }}
        PR_EVENT_NUMBER: ${{ inputs.pr_event_number }}
      run: |
        podman run --env-host --network=host --privileged --device /dev/fuse -v $PWD:/bluebuild \
        ghcr.io/blue-build/cli:v0.7.1-alpine build --push ./config/${{ inputs.recipe }} \
        --registry ${{inputs.registry}} --registry-namespace ${{inputs.registry_namespace}}
