name: 'BlueBuild'
description: 'Build a custom OS image'
inputs:
  recipe:
    description: 'recipe.yml file to build'
    required: true
    default: 'recipe.yml'
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v1
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    - uses: actions/checkout@v4
    - uses: sigstore/cosign-installer@v3.3.0
    - name: Install Cargo
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Install BlueBuild tool
      shell: bash
      run: |
        cargo install blue-build --locked
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get install -y buildah skopeo
    - name: Build Image
      shell: bash
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        PR_EVENT_NUMBER: ${{ github.event.number }}
        REGISTRY_TOKEN: ${{ github.token }}
      run: |
        bb build --push ./config/${{ inputs.recipe }}